### ISSUE TITLE
跳过的项目设置

### ISSUE THREAD

**Issue by blackdarks** [AutoXuexiPlaywright/AutoXuexiPlaywright#11]
比如我想跳过专项答题，是不是在设置这栏内#专项答题 即可？ 如果有多的模块要跳过，是不是eg：#专项答题#每周答题

需要加双引号吗？

**Comment by arenekosreal** [comment]
跳过专项答题直接写 专项答题 就好
跳过专项答题和每周答题就写 专项答题#每周答题
不需要引号

**Comment by arenekosreal** [comment]
没有问题的话就关闭这个 issue 了，如果还有需要问的可以直接在后面继续写或者开个新的

**Comment by blackdarks** [comment]
非常感谢你的解答，感谢大佬的作品，在这涩涩的冷风中带来的温暖
