### ISSUE TITLE
如何调试滑动验证码求解脚本

### ISSUE THREAD

**Issue by yurhett** [AutoXuexiPlaywright/AutoXuexiPlaywright#50]
作者您好，感谢您贡献这一伟大的项目，我正在调试自己的代码，调试过程中发现但验证码不能稳定触发，这为验证码求解器的调试带来了很大阻碍，请问您是如何调试验证码解决器的，是否有一些奇技淫巧，希望您能不吝赐教，提前感谢您的解答！

**Comment by arenekosreal** [comment]
我也有没有什么好办法，目前的验证码解决办法非常的简陋，并且由于不容易触发验证码也并没有经过实际测试
对于个人使用来说也不容易到触发验证码的地步所以目前关注点不在这上面

**Comment by yurhett** [comment]
感谢回复，学习强国网页版触发封号的原因是弹出验证码没有及时处理，对于防封来说，解决验证码问题至关重要。我这边发现了一个稳定触发方法：在每日答题中手机和电脑使用不同的IP属地即可触发。
