### ISSUE TITLE
封号问题请教

### ISSUE THREAD

**Issue by haipengzzz** [AutoXuexiPlaywright/AutoXuexiPlaywright#51]
### Your request
你的请求

请问一下大佬，这个项目是否对封号进行了解决？目前已经启动在运行了。稳定性如何？

**Comment by arenekosreal** [comment]
没有应对封号的措施
就是模拟浏览器操作，自用的频率倒是没见过触发封号的，当然这种都是第三方工具，只能说都有概率
稳定性方面由于是操作浏览器，最大的问题就是网页布局更改导致找不到位置

**Comment by haipengzzz** [comment]
> 没有应对封号的措施 就是模拟浏览器操作，自用的频率倒是没见过触发封号的，当然这种都是第三方工具，只能说都有概率 稳定性方面由于是操作浏览器，最大的问题就是网页布局更改导致找不到位置

同样使用js 油猴版本的插件是触发封号的。这是一个比较纠结的问题。
