### ISSUE TITLE
[Bug]: 前两天还可以刷出十几分, 今天刷不了了, 可以麻烦看看吗, 感谢

### ISSUE THREAD

**Issue by liuzhuoling2011** [AutoXuexiPlaywright/AutoXuexiPlaywright#66]
### Exists on latest code
在最新源代码上仍然存在

- [X] I am using latest code
我正在使用最新的源代码

### Your OS platform
你的操作系统平台

Windows

### Expected Behavior
预期的行为

可以拿20分左右

### Actual Behavior
实际行为

只拿到了登录1分

### What have you done
你做了什么操作

无

### Log output
程序日志输出

![image](https://github.com/AutoXuexiPlaywright/AutoXuexiPlaywright/assets/8407297/b7243e69-5572-4ab4-8306-d39541a64545)

**Comment by arenekosreal** [comment]
这个看起来应该是一个看视频回答的题目，等较长时间后就会让你写一下答案了
具体请到设置里面打开调试模式附带一下浏览器的网页内容
