### ISSUE TITLE
安装依赖问题

### ISSUE THREAD

**Issue by blackdarks** [AutoXuexiPlaywright/AutoXuexiPlaywright#8]
按照流程装好python3 和poetry成功，然后不知道所谓的仓库是哪个目录，在Windows下运行poetry install错误，提示没有xx.tom文件，无奈只好pip install xx.whl，不知道流程是否有问题

**Comment by arenekosreal** [comment]
仓库就是 git clone 之后得到的文件夹，跳过依赖安装的话将可能导致无法运行
建议了解一些 git 的基本概念：
https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E8%8E%B7%E5%8F%96-Git-%E4%BB%93%E5%BA%93
